java_test(
    name = "hello",
    srcs = glob(["*.java"]),
    test_class = "com.sebelino.hello.HelloWorldTest",
    deps = [
        "//src/main/java/com/sebelino/hello",
        "@maven//:junit_junit",
    ],
)
