services:
  app:
      image: "bazel-hello-example:latest"
      working_dir: /app
      volumes:
        - /tmp/bazelcache/outputroot-bazel-hello:/root/.cache/bazel
        - /tmp/bazelcache/bazelisk-bazel-hello:/root/.cache/bazelisk
      networks:
        - no-internet
networks:
  no-internet:
    driver: bridge
    internal: true
