java_test(
    name = "hello",
    srcs = glob(["*.java"]),
    test_class = "se.tink.hello.HelloWorldTest",
    deps = [
        "//src/main/java/se/tink/hello",
        "@maven//:junit_junit",
    ],
)
